dist: trusty
language: scala
scala:
- 2.12.8
jdk:
- oraclejdk8
script:
- sbt test
deploy:
  skip_cleanup: true
  provider: script
  script: "./.travis/deploy.sh $TRAVIS_TAG"
  on:
    tags: true
env:
  global:
  # BINTRAY_SNOWPLOW_MAVEN_USER
  - secure: KRvEDSV6tIh2kLvDpaoGDjFvaDflpVwfhWydsS6LBHWb2yjLdXROwnXHn0rL8bubyim95yO1TcdpDeesDNp1xxaPAKR2ZsO+hEyPA41PpVuRv+UBWU1GFxNvgP87AbgDlgMCh0LDdkqhvvyzWZnN1nIwvVjgOT9bKdbF0O77MDZg0g+GIns8Cg//mlLFl65/Id/WX78Cp/m2Wc/hfmIIM6yfAcFr39mGX54m9oNzsvegXllqFPaBcMwn4TzT5hwPone5CIzdirjtPyYXD7RaKu0BwWHSqJeY/1t2e1qfyyLQSjQoEjOPgybRffh6hqTnjRmu+Nl7YJYaeewteCsWZlv9Qrdqi/I2nAasGfX+iFFc2+6UbFCfg+Yo2mYHhDTHLd/Nh7IUjdrgffKvs7iQR0f1x6jTxvUZdb9A+9h8ANDJE79xcqwiJ3FAkNhrVAYQYp8fHSleSYmWDgBXrj/Z3OuYMZAMCD+bCjSkfygE66txQDJRAyvln48R0XNhlQ7Q9ZLezJh79zAY31E4NLO0FrhNiEyuAZQShy0SPRpcjq1LjTFOoAEsnLLtj3PzMSRDvOIwtJlUr4d2xPhB8kKLk3q4S/+235y5ZXWM6/ivzcee5Q0Qyq7wUiRkAlWeZHcNRelXua19VgDvuc4UM9az56jpRVeHpHpwW/ZtjPaemyw=
  # BINTRAY_SNOWPLOW_MAVEN_API_KEY
  - secure: 3zUDcOkBrG836fbhVEoFmeYozsCTCy08/zvkBi/pUSuMpn9srsP13vH3OXsCBZf+QGuAcRDnvGuJOK1YghNV0c12WSIbMX/yYQO3nwpMbxUqwJkoVj7ENg8j3p1hIRpZ3i/DpjegrS0b9++OL5wXFwka8rNnxeIavlDYN0rl9Xz0ACvuFdqlxOZmXxGPXTzjglOSyiJyu97/dHdBWxM9rC0GlBYu4UMIJKWJ9ELeO2RA7DZ3vARS0tnhbfXQbIQgAtfqa8h1qDfKmt48u+iLKMSmqmfF/9Vao6GvyCBsqR9YY4O2C9PSMliFtn+5y3HnPMZ2p+cmkXRx/aIb0+mpqGREHKqNCwWbM02/K74w+hi1jJnZAZsHDReWcbMwVZgb5YG7qLP/zT1z4N4Gl5JwyphzcMMKV11yDpW0ecjlm50rvcfFVGov7vjuNOS+OtAfNnFGrdUylafgkX86tetLF5xwX7O14uLIrb16cvkwELEJqRhg4prx57mo7VbuzNzEMpmDGT9xEtyzLg+1l/c6C/KbhcDA+TRMtJn3IFqQKeoxu9wwik7EDPh7hPAyzGMTheDu2SVFXtyVdXM4r/XH46XrQioKgDorA3Q2nJxx374IxsStUt34i1NO1hkkaIJrWa2gcRqZCal5Gx7VtXg2QpFs08uCHD6k+U+o/exb1hM=
  - SONA_USER=snowplow
  # SONA_PASS
  - secure: yJ6Jul5WWnPah+gYkORsesNqmclpiVCgI7jdFXrmswJR0XF8qQvynUG6Al1VuaXoLy2mlFp/F6Hr0z22ZHgEVxnYCZtLpfp1krdUaj80xtZPP70dNcVwpEgS3ZAavT1CFyiq5KmJ1N9CPHGWfOIPCSgS4OhDzpbpM276mI4TvwnYA3gzwfZBKs2DoDST0IgiSL/KHnoo23rZscDmaLpFsfCoSCNt9K8RQ+HkktYaHnxOJjeUK4IID+Q3jR13joYMEmTCi0J1jErwpeqNZufyMWdkmTChjeSipfc6wp6n2HiaGwpiq4zO5RGUsQN3wvO0TH98eg09mVnW1loB2JLstXy6FiwQ7YNqGsS00HdsRQZN2r0s3iTht1nPHSQDuLpBUg9LVQAwwJ94tbLzf93LF269YZTYsiWy68/KRz1XRDTTXUGXmSqnfc3VxlPchiaw29xOIv+uRKYLy7ti1w1gXkJYyRwZXN6e5LDkZLmso7hIt7tWXTYYjLhhZoKvzRqL9vzFShmuAHIPD6qFXk+DixWNclo4/kbCV5+5CGsj5RcjxQOSEuRJPc3qDQlqml7dJUYVbR9Ov55O90umVpUpUDlsFF0EytM+M2+55ahettqdLesGaFDkyJotEhcWniFdJ8pRhRDiEJ39HA21y9e0CFwXLKy7bt25uQN+OEMLlvk=
